### ISSUE TITLE
Invert map

### ISSUE THREAD

**Issue by DashCee** [1pulse/Factorio-Biter-Battles#35]
Invert the direction of one of the teams, to produce a mirror-map, so we can really see how different teams evolve differently over time. Would ideally just be a case of multiplying the x co-ord of all co-ords under y=0 by -1 to flip all tiles under spawn to the other side.

**Comment by guymaor86** [comment]
we can close this issue as it was resolved

**Comment by mysticamber** [comment]
I can't close, but this is resolved in #48

**Comment by guymaor86** [comment]
@DashCee want to close this?
