### ISSUE TITLE
Chat commands broken 

### ISSUE THREAD

**Issue by DashCee** [1pulse/Factorio-Biter-Battles#36]
Something is causing chat commands to break. This is really detrimental when players are looking for our discord. 02:30 UTC 12/12/2020 for server logs. I also have screenshots of the lack of response in-game

**Comment by 1pulse** [comment]
too old for logs I think, not sure to understand, u have screenshot u said?  how to reproduce?

**Comment by mysticamber** [comment]
Resolved
