### ISSUE TITLE
Add Threat and Evo Stats to Spectator View (only in Tournament Mode)

### ISSUE THREAD

**Issue by kajendra** [1pulse/Factorio-Biter-Battles#66]
Spectators can't see the Threat and Evo.
A workaround is to join a team and then go back to Spectator View, but this is not possible in Tournament Mode.
It was suggested not to implement this on the public servers (non-tournament Mode).

Suggested fix is to enable Spectators to see Threat and Evo only in Tournament Mode.

I want to work on this enhancement!

**Comment by guymaor86** [comment]
today when you guys were in a tournament i could see the evo and threat
it might be working
we can test it out tomorrow

**Comment by kajendra** [comment]
Yes, this is working now... interesting..
Tempted to implement this with a time limit in non-tournament mode.
(after 3 min of being a spectator, you can see Evo / Threat)

But if people don't like that, we can just close this issue.
