### ISSUE TITLE
Autostash doesn't work

### ISSUE THREAD

**Issue by kajendra** [1pulse/Factorio-Biter-Battles#71]
When pressing the Wooden Chest button at the top of the screen.
This button should Sort your inventory into chests.
It does not work.

The line is located here: 
https://github.com/1pulse/Factorio-Biter-Battles/blob/68b13e4fb83259c149fde9fadc6bbbc4f0bb26ca/modules/autostash.lua#L167

I can't understand why it's not working. It's not getting inside the loop.

Not sure if this is by design, tried a few things and still a little lost here...

**Comment by mysticamber** [comment]
Disabled autostash. It's not really designed for bb
